version = 1


exclude_patterns = [
    "web/public/charting_library/**,",
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/jsumhk/baseapp"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "shell"
enabled = true
